name: Node.js CI - Run Test Cases

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test
      - name: Check if app builds successfully
        run: |
          npm runn build
          exit 1
